### ISSUE TITLE
Update String Interpreter to Handle Uppercase Inputs and Allow Custom SVG Images

### ISSUE THREAD

**Issue by dabruhce** [dabruhce/combo-clip-composer#3]
## Issue Description
Currently, the system cannot interpret uppercase/lowercase inputs F = fp, due to using the simplest way to populate images. It will cause issues as we cannot rely on the user's OS to differentiate between uppercase and lowercase strings. The string interpreter needs to be updated to translate all inputs, including B, DB, D, DF, F, UF, U, and UB, to their corresponding lowercase SVG image files (e.g., fp.svg).

## TODO Tasks
- [x] Update the string interpreter to handle uppercase inputs and translate them to their corresponding lowercase SVG image files.
- [x] Create a test to validate that users can swap in custom SVG images.
- [x] Add an example of how to add custom images to the readme.md file.

## Additional Information
Ensure the updated functionality is thoroughly tested to work as expected.

## Acceptance Criteria
- The string interpreter code is updated to handle all inputs, including uppercase inputs.
- The functionality is tested thoroughly and works as expected.
- The test for custom SVG images is created and passes successfully.
- The readme.md file includes an example of how to add custom images.
