### ISSUE TITLE
Add Customization Options for Text and Image Elements

### ISSUE THREAD

**Issue by dabruhce** [dabruhce/combo-clip-composer#4]
## Description
The current implementation of the application does not provide enough flexibility for users to customize text and image elements. This issue aims to add various customization options that will allow users to configure font, font size, color, position, spacing, padding, and margins for text and image placements. Additionally, users will be able to inline color changes and newline, and preview elements in a simple Electron editor. The issue will also add support for text animation and dropshadow effects.

## TODOs:
- [ ] Allow the configuration of font, font size, color, and position
- [ ] Add method for users to inline color changes and newline
- [ ] Provide better control of spacing, padding, and margins in text and image placements
- [ ] Implement a preview feature in a simple electron editor
- [ ] Add support for text animations
- [ ] Implement text dropshadow effect; this code would probably work
````javascript
ctx.shadowColor = #12312;
ctx.shadowBlur = 0;
ctx.shadowOffsetX = -2;
ctx.shadowOffsetY = 3;
ctx.fillText ...
````
## Acceptance Criteria
Users can configure font, font size, color, and position for text and image elements
Users can inline color changes and newline with simple methods
Users have better control over spacing, padding, and margins in text and image placements
Users can preview elements in a simple Electron editor
Text animation is supported
Dropshadow effect is implemented using the provided code

## Additional Information
Please feel free to ask questions or provide feedback on this issue.
